services:
  postgres:
    ports: []

  redis:
    ports: []

  osrm:
    ports: []

  backend:
    ports: []
    environment:
      DEV_MODE: "false"
      SOCKET_CORS_ORIGIN: https://taxi.cognilabs.org

  passenger:
    ports: []

  driver:
    ports: []

  admin:
    ports: []

  gateway:
    ports:
      - "80:80"
